name: kebo_app
description: A new Flutter project.
publish_to: none
version: 1.0.2+26
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.2.1
  intl: ^0.19.0
  freezed_annotation: ^2.2.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_annotation: ^4.8.0
  flutter_lints: ^2.0.1
  injectable_generator: ^2.1.4
  json_serializable: ^6.6.1
  flutter_launcher_icons: ^0.12.0
  flutter_bloc: ^8.1.2
  either_dart: ^1.0.0
  injectable: ^2.1.0
  image_cropper: ^5.0.0
  get_it: ^7.2.0
  permission_handler: ^10.2.0
  image_picker: ^0.8.6+4
  formz: ^0.6.0
  url_launcher: ^6.1.10
  timeago: ^3.3.0
  cupertino_icons: ^1.0.5
  flash: ^3.0.5+1
  flutter_feather_icons: ^2.0.0+1
  flutter_svg: ^2.0.2
  pin_code_fields: ^8.0.1
  cached_network_image: ^3.2.3
  device_preview: ^1.1.0
  uuid: ^3.0.7
  pull_to_refresh: ^2.0.0
  tuple: ^2.0.2
  shimmer: ^2.0.0
  flutter_native_splash: ^2.2.19
  get: ^4.6.5
  sentry_flutter: ^7.7.0
  flutter_secure_storage: ^9.0.0
  provider: ^6.0.0
  connectivity_plus: ^4.0.1
  lottie: ^2.5.0
  flutter_displaymode: ^0.6.0
  flutter_animate: ^4.2.0
  percent_indicator: ^4.2.3
  equatable: ^2.0.3
  device_info: ^2.0.2
  package_info_plus: ^4.0.2
  badges: ^2.0.2
  font_awesome_flutter: ^10.1.0
  dio: ^5.4.0
  local_auth: ^2.3.0
  firebase_core: ^2.15.0
  video_thumbnail: ^0.5.3
  carousel_slider: ^5.0.0
  collection: ^1.18.0
  animated_text_kit: ^4.2.2
  firebase_auth: ^4.7.2
  google_sign_in: ^6.2.1
  webview_flutter: ^4.2.2
  sign_in_with_apple: ^5.0.0
  pattern_formatter: ^4.0.0
  flutter_slidable: ^3.0.1
  share_plus: ^7.2.1
  encrypt: ^5.0.3
  syncfusion_flutter_charts:
    git:
      url: 'https://github.com/iktakahiro/flutter-widgets.git'
      ref: support-flutter-3.24.0
      path: packages/syncfusion_flutter_charts
  custom_date_range_picker:
    path: packages/custom_date_range_picker
  intl_phone_number_input:
    path: packages/intl_phone_number_input
  shake: ^2.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
  - assets/lotties/
  - assets/icons/
  - assets/mockup/
  - assets/images/
  fonts:
  - family: Outfit
    fonts:
    - asset: assets/fonts/Outfit-Thin.ttf
      weight: 100
    - asset: assets/fonts/Outfit-ExtraLight.ttf
      weight: 200
    - asset: assets/fonts/Outfit-Light.ttf
      weight: 300
    - asset: assets/fonts/Outfit-Regular.ttf
      weight: 400
    - asset: assets/fonts/Outfit-Medium.ttf
      weight: 500
    - asset: assets/fonts/Outfit-SemiBold.ttf
      weight: 600
    - asset: assets/fonts/Outfit-Bold.ttf
      weight: 700
    - asset: assets/fonts/Outfit-ExtraBold.ttf
      weight: 800
    - asset: assets/fonts/Outfit-Black.ttf
      weight: 900
  - family: ReadexPro
    fonts:
    - asset: assets/fonts/ReadexPro-ExtraLight.ttf
      weight: 200
    - asset: assets/fonts/ReadexPro-Light.ttf
      weight: 300
    - asset: assets/fonts/ReadexPro-Regular.ttf
      weight: 400
    - asset: assets/fonts/ReadexPro-Medium.ttf
      weight: 500
    - asset: assets/fonts/ReadexPro-SemiBold.ttf
      weight: 600
    - asset: assets/fonts/ReadexPro-Bold.ttf
      weight: 700

flutter_intl:
  main_locale: es
  enabled: true
  arb_dir: lib/core/l10n
  output_dir: lib/core/l10n/generated
