// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSgitaMPB72dEwdcWoLvfdx21i9Kv3uyg',
    appId: '1:63440265041:web:2116316682605997b4fd70',
    messagingSenderId: '63440265041',
    projectId: 'kebo-test',
    authDomain: 'kebo-test.firebaseapp.com',
    storageBucket: 'kebo-test.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUpzI-HlNZ8c6pmGckICgEstIfj_9qkeo',
    appId: '1:63440265041:android:d92c523075ad831fb4fd70',
    messagingSenderId: '63440265041',
    projectId: 'kebo-test',
    storageBucket: 'kebo-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHZtQbteRDa_KNAgjtgkODriehspb4plo',
    appId: '1:63440265041:ios:595c11d2b2c4dd85b4fd70',
    messagingSenderId: '63440265041',
    projectId: 'kebo-test',
    storageBucket: 'kebo-test.appspot.com',
    androidClientId: '63440265041-6itfvs0clu7t6ebcbg5ph5qes1rtvovs.apps.googleusercontent.com',
    iosClientId: '63440265041-lnpbai6k3u80qqk9ko773pfhp6cqn5bb.apps.googleusercontent.com',
    iosBundleId: 'vn.ego.client',
  );
}
